version: "3"
services:
  opengrok-llvm:
    container_name: opengrok-llvm
    image: opengrok/docker:latest
    ports:
      - "9090:8080/tcp"
    environment:
      SYNC_PERIOD_MINUTES: '1501'
    volumes:
      # source code
      - '/groksrc/llvm-project/:/opengrok/src/'
      # index and other things for source code
      - '/opengrok/data/llvm-project/:/opengrok/data/'

  opengrok-iree:
    container_name: opengrok-iree
    image: opengrok/docker:latest
    ports:
      - "9091:8080/tcp"
    environment:
      SYNC_PERIOD_MINUTES: '1401'
    volumes:
      - '/groksrc/iree/:/opengrok/src/'
      - '/opengrok/data/iree/:/opengrok/data/'

  opengrok-torchmlir:
    container_name: opengrok-torchmlir
    image: opengrok/docker:latest
    ports:
      - "9093:8080/tcp"
    environment:
      SYNC_PERIOD_MINUTES: '1301'
    volumes:
      - '/groksrc/torch-mlir/:/opengrok/src/'
      - '/opengrok/data/torch-mlir/:/opengrok/data/'

  opengrok-pytorch:
    container_name: opengrok-pytorch
    image: opengrok/docker:latest
    ports:
      - "9094:8080/tcp"
    environment:
      SYNC_PERIOD_MINUTES: '1201'
    volumes:
      - '/groksrc/pytorch/:/opengrok/src/'
      - '/opengrok/data/pytorch/:/opengrok/data/'

  opengrok-ireeamdaie:
    container_name: opengrok-ireeamdaie
    image: opengrok/docker:latest
    ports:
      - "9095:8080/tcp"
    environment:
      SYNC_PERIOD_MINUTES: '1201'
    volumes:
      - '/groksrc/iree-amd-aie/:/opengrok/src/'
      - '/opengrok/data/pytorch/:/opengrok/data/'

